<?php

namespace App;

/*
 * Реализуйте механизм валидации для каждого элемента DOM, который проверяет переданные атрибуты на допустимость.

<?php

$img1 = new HTMLImgElement(['class' => 'rounded', 'src' => 'path/to/image']);
$img1->isValid(); // true

$img2 = new HTMLImgElement(['class' => 'rounded', 'href' => 'path/to/image']);
$img2->isValid(); // false

$button1 = new HTMLButtonElement(['class' => 'rounded', 'type' => 'button']);
$button1->isValid(); // true

$button2 = new HTMLButtonElement(['class' => 'rounded']);
$button2->isValid(); // false
src/HTMLElement.php
Определите абстрактный метод isValid()

src/HTMLImgElement.php
Реализуйте метод isValid, который проверяет соответствие между переданными атрибутами и допустимыми атрибутами.
Для тега Img допустимыми являются: name, class, src. Причём name и class допустимы для любого элемента.
 Поэтому информация о них должна находиться в базовом классе.

src/HTMLButtonElement.php
Реализуйте валидацию по аналогии как для тега Img. Для тега Button допустимыми являются: name, class, type.
 Причём атрибут type, является обязательным и может принимать одно из доступных значений: button, submit, reset.
class HTMLImgElement extends HTMLElement
{
    private const ATTRIBUTE_NAMES = ['src'];

    public static function getAttributeNames()
    {
        return array_merge(parent::getAttributeNames(), static::ATTRIBUTE_NAMES);
    }

    // BEGIN
    public function isValid()
    {
        $names = array_keys($this->getAttributes());
        $diff = array_diff($names, $this->getAttributeNames());

        return empty($diff);
    }
    // END
}
Подсказки
array_diff
 */

class HTMLImgElement extends HTML3Element
{
    private const ATTRIBUTE_NAMES = ['src'];

    public static function getAttributeNames()
    {
        return array_merge(parent::getAttributeNames(), static::ATTRIBUTE_NAMES);
    }

    // BEGIN (write your solution here)
    public function __construct($attributes = [])
    {
        parent::__construct($attributes);
    }

    public function getAttributes()
    {
        return parent::getAttributes(); // TODO: Change the autogenerated stub
    }

    public function isValid(): bool
    {
        return parent::isValid(); // TODO: Change the autogenerated stub
    }
    // END
}
